### ISSUE TITLE
#strapi > media library files automatically deleted

### ISSUE THREAD

**Issue by clyptomania** [suga-data/MAK#31]
### Possible Source of Problem
- everytime strapi git is updated and pushed to remote repository, the media library overwrites and deletes media content

**Comment by valid-void** [comment]
SOLUTION:
 we use cloudinary as a service to handle media files.

> create an account at cloudinary.com

> install strapi-provider-upload-cloudinary
https://www.npmjs.com/package/strapi-provider-upload-cloudinary

> details: follow these instruction
https://strapi.io/blog/adding-cloudinary-support-to-your-strapi-application

> don't forget to update heroku config vars in order to connect with cloudinary
